name: myapp
description: "A new Flutter project."
# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.0  # Gestione della localizzazione e formattazione delle date
  fl_chart: ^0.69.2  # Grafici per rappresentare i dati
  flutter_secure_storage: ^9.2.2  # Ultima versione disponibile
  logger: ^2.5.0  # Ultima versione disponibile
  path_provider: ^2.1.5  # Necessario per l'archiviazione sicura

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Torna alla versione compatibile

flutter:
  uses-material-design: true
